# Site settings
title: Andrew Kairy's Professional thoughts
header-img: img/home-bg.png
email: andrewkairys@gmail.com
copyright_name: Logicianmagician
description: > # this means to ignore newlines until "baseurl:"
  Professional Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Logicianmagician
learn_profile: Logicianmagician
email_username: andrewkairys@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
